create table if not exists public.research_papers (
 id uuid primary key default gen_random_uuid(), title text not null unique, status text not null check(status in('Published','Accepted')), abstract text not null default '', publication_url text, venue text not null, publisher text not null check(publisher in('IEEE','Springer')), publication_year integer not null check(publication_year between 1900 and 2200), doi text not null, authorship_label text not null check(authorship_label in('First author','Second author','Co-author')), author_position integer not null check(author_position>0), author_count integer not null check(author_count>0), sort_order integer not null default 0, visible boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check(author_position<=author_count)
);
drop trigger if exists research_papers_set_updated_at on public.research_papers; create trigger research_papers_set_updated_at before update on public.research_papers for each row execute function public.set_updated_at();
alter table public.research_papers enable row level security;
create policy "visible research is public" on public.research_papers for select using(visible or public.is_cms_admin());
create policy "admins create research" on public.research_papers for insert with check(public.is_cms_admin());
create policy "admins update research" on public.research_papers for update using(public.is_cms_admin()) with check(public.is_cms_admin());
create policy "admins delete research" on public.research_papers for delete using(public.is_cms_admin());

insert into public.research_papers(title,status,abstract,publication_url,venue,publisher,publication_year,doi,authorship_label,author_position,author_count,sort_order) values
('REMP: A Swin Transformer-Powered Approach to Classifying Rare and Endangered Medicinal Plants','Published','A customized Swin Transformer classified 16 rare and endangered medicinal plant species with 98.46% accuracy, supporting technology-assisted identification and conservation.','https://ieeexplore.ieee.org/document/11171802','2025 International Conference on Quantum Photonics, Artificial Intelligence, and Networking (QPAIN)','IEEE',2025,'10.1109/QPAIN66474.2025.11171802','First author',1,8,1),
('Explainable Deep Learning Paradigms for Nitrogen Deficiency Detection: Multi-Crop Assessment of CNN-Based Models for Agricultural Intelligence','Published','An explainable multi-crop assessment using SE-ResNeXt and Grad-CAM, achieving 95.23% classification accuracy across four crop datasets.','https://ieeexplore.ieee.org/document/11491378','2025 28th International Conference on Computer and Information Technology (ICCIT)','IEEE',2025,'10.1109/ICCIT68739.2025.11491378','Second author',2,5,2),
('Detection of Lemon Leaf Diseases Using Inception V3-Based Machine Learning Model','Published','A comparative deep-learning study of lemon leaf disease classification in which Inception V3 achieved 86.94% validation accuracy, with explainability and augmentation identified as paths toward stronger precision-agriculture systems.','https://link.springer.com/chapter/10.1007/978-3-032-04539-3_10','International Conference on Computational Intelligence and Information Retrieval (ICCIIR 2025) · LNNS 1617','Springer',2026,'10.1007/978-3-032-04539-3_10','Co-author',8,9,3),
('Forecasting Air Quality: A Comprehensive Survey of Air Pollution Prediction Methods and Applications','Published','A survey of statistical, machine-learning, and deep-learning approaches to air-quality prediction, covering their comparative strengths, limitations, interpretability, and opportunities for real-time monitoring.','https://link.springer.com/chapter/10.1007/978-3-032-02790-0_29','International Conference on Computational Intelligence and Information Retrieval (ICCIIR 2025) · LNNS 1593','Springer',2026,'10.1007/978-3-032-02790-0_29','Co-author',7,12,4)
on conflict(title) do nothing;
